services:
  server:
    image: ghcr.io/lncrawl/lightnovel-crawler:latest
    ports:
      - "23457:8080"
    command: -ll server -p 8080
    environment:
      - LNCRAWL_DATA_PATH=/data
      - DATABASE_URL=${DB_URL}
    volumes:
      - ./appdata:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "3.50"
          memory: 5G
        reservations:
          cpus: "2.00"
          memory: 3G